### ISSUE TITLE
add docs website

### ISSUE THREAD

**Issue by Hebilicious** [Hebilicious/form-actions-nuxt#52]
### Describe the feature

Create a dedicated website for the docs and clean-up the README.

### TODO

- [ ] Deploy on CFP
- [ ] Update module page
- [ ] Publish on Twitter/Social etc

### Additional information

- [X] Would you be willing to help implement this feature?
